const defaults = {
    "horizontalFadingStart": "20",
    "horizontalFadingEnd": "65",
    "backgroundColor": "#d0d2c0",
    "fontSize": "10",
    "horizontal": "20",
    "vertical": "43",
    "fontColor": "#29363a",
    "italic": false,
    "bold": false,
    "dropShadow": true,
    "shadowDistance": "0.5",
    "shadowAngle": "1",
    "shadowBlur": "1",
    "shadowColor": "#000000",
    "highlightingEnabled": true,
    "highlightingColor": "#99bbcc",
    "font": "Rubik",
    "method": "Random wiki articles summarries",
    "symbols": "qwertyuiopasdfghjklzxcvbnm",
    "numberOfSymbols": "10",
    "numberOfWords": "10",
    "numberOfWordsInChain": "10",
    "numberOfSentences": "1",
    "currentSentenceNumber": "1"
}